// SPDX-FileCopyrightText: 2021 Visne
// SPDX-FileCopyrightText: 2021 metalgearsloth
// SPDX-FileCopyrightText: 2021 moonheart08
// SPDX-FileCopyrightText: 2022 Paul Ritter
// SPDX-FileCopyrightText: 2022 Rinkashikachi
// SPDX-FileCopyrightText: 2022 mirrorcult
// SPDX-FileCopyrightText: 2022 wrexbe
// SPDX-FileCopyrightText: 2023 Morb
// SPDX-FileCopyrightText: 2025 FrauzJ
//
// SPDX-License-Identifier: MIT

using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;

         public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);


            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Server);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-syndicate"));
            AnnounceMethod.SetItemMetadata(2, AdminAnnounceType.Syndicate);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-wizard"));
            AnnounceMethod.SetItemMetadata(3, AdminAnnounceType.Wizard);

            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            var selectedType = (AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station;
            Announcer.Editable = selectedType == AdminAnnounceType.Station || selectedType == AdminAnnounceType.Syndicate || selectedType == AdminAnnounceType.Wizard;

            switch (selectedType)
            {
                case AdminAnnounceType.Station:
                    Announcer.Text = _localization.GetString("admin-announce-announcer-default");
                    break;
                case AdminAnnounceType.Syndicate:
                    Announcer.Text = _localization.GetString("admin-announce-type-syndicate-default");
                    break;
                case AdminAnnounceType.Wizard:
                    Announcer.Text = _localization.GetString("admin-announce-type-wizard-default");
                    break;
            }

        }
    }
}
